[project]
name = "asr-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.0",
    "funasr>=1.2.0",
    "librosa>=0.11.0",
    "modelscope>=1.21.0",
    "pypinyin>=0.55.0",
    "soundfile>=0.13.1",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "uvicorn>=0.44.0",
    "qwen-asr",
    "mlx[cuda]==0.26.3",
    "mlx-qwen3-asr==0.3.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
